commitizen:
  bump_message: '[bump] from $current_version to $new_version'
  customize:
    bump_map:
      break: MAJOR
      bug fix: PATCH
      config: PATCH
      feature: MINOR
    bump_pattern: feature|bug fix|config|break
    example: '[bug fix] (README.md) Fix Typo'
    message_template: '[{{ type }}]{% if changed_scope %} ({{ changed_scope }}){%
      endif %} {{ message }}'
    questions:
    - choices:
      - name: new feature
        value: feature
      - name: bug fix
        value: bug fix
      - name: config
        value: config
      - name: breaking changes
        value: break
      message: "Select type:"
      name: type
      type: list
    - message: "Changed files or directory scope:"
      name: changed_scope
      type: path
    - message: "Input message:"
      name: message
      type: input
  name: cz_customize
  tag_format: v$major.$minor.$patch$prerelease
  version: 0.0.1
  version_files:
  - project.yaml:version
